### ISSUE TITLE
Question: Are any of the EXIF data exposed on the model ?

### ISSUE THREAD

**Issue by sebastiandammark** [huwred/MediaInfo-14#1]

**Comment by huwred** [comment]
See https://github.com/huwred/MediaInfo-14?tab=readme-ov-file#onsave-notification

**Comment by sebastiandammark** [comment]
Yeah, I’ve red that part, but how do I get access to f-nummer, shutterspeed and exposure ?

**Comment by huwred** [comment]
I don't have any plans to extend it, but you could download the project and that for yourself.
You would just need to parse it in the AddExifFromImageHandler.

Adding something like this should work
```
                if (jpgInfo != null && !tags.ContainsKey("exifShutter"))
                {
                    _logger.LogDebug($"Found {publishedItem.Name} jpgInfo");
                    var dateStr = jpgInfo?.GetDescription(ExifDirectoryBase.TagShutterSpeed);
                    if(dateStr != null)
                    {
                        tags.Add("exifShutter", dateStr);
                    }  
                }
```
There is intellisense for the tags so should be able to find what you want.
